import type { Metadata } from "next";
import "./globals.css";
import { raleway } from "@/utils/front";
import { AuthProvider } from "@/contexts/AuthContext";


export const metadata: Metadata = {
  title: "StreamLand",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
